/****** Object:  Table [dbo].[Pracownik]    Script Date: 29.12.2022 16:28:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pracownik](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[imie] [nchar](10) NOT NULL,
	[nazwisko] [nchar](10) NOT NULL,
	[adres] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Pracowniks] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
